---
title: "Customer Churn Analysis"
author: "Adetunji Elegushi"
date: "`r Sys.Date()`"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(kableExtra)
library(pacman)
p_load(tidyverse,lubridate, janitor,knitr, kableExtra,patchwork,gt,gtextra)

customer_churn <- read_csv("~/customer churn/telecom_customer_churn.csv") %>% 
  clean_names()
```

 `r text_spec("Introduction",bold=T,font_size = 20,color="orange")`

 
This is a Telecommunication company that provides phone and internet services to `r text_spec(format(nrow(customer_churn),big.mark=","),bold= T,color = "green",font_size = 10 )` customers in California, this project will focus on knowing why customers are leaving the company so that the company will be able to use insights from this analysis to prevent future churn.

#### Why do companies try to know customer who leave and those who stayed?

* Utilizes these insights to predict customers who are likely to churn

* Gainsight and understands the negative impact that churn rate can have on company profits.

* To identifies the causes for churn and works to resolve those issues.

* To engages with customers to foster relationships

 


Recommended Analysis

How many customers joined the company during the last quarter? How many customers joined?

What is the customer profile for a customer that churned, joined, and stayed? Are they different?

What seem to be the key drivers of customer churn?

Is the company losing high value customers? If so, how can they retain them?
